### ISSUE TITLE
choose name

### ISSUE THREAD

**Issue by wesleymostien** [MOS-10/smicklr#11]
- search google
- check username : http://knowem.com/, http://checkusernames.com/, https://www.namecheckr.com/

Facebook : A–z, 0–9, "." (> 5 chars) = https://www.facebook.com/ ...
Instagram : A–z, 0–9, ".", "_" = https://www.instagram.com/ ...
Twitter : all chars (no spaces, < 15 chars) = https://twitter.com/ ...
LinkedIn
YouTube = https://www.youtube.com/user/ ...
GitHub

- check domain : .com, .app (.buzz, .biz, .net, .me, .web) => https://www.name.com/domains
- app stores : Android, iOS, Mac

**Comment by wackowizzard** [comment]
1. everee / evry
0. listr
0. peeq / sneeq-a-peeq
0. bizzybee / bizzeebee / bizzyme / bizzzee
0. beeq / beeqeepr
0. beezneez / beesness
0. beeyond
0. honneybee / honee / honnee / honeebee / honny 
0. beecauze / beecauz / beecoz
0. eezee
0. stuffr / stuffluv
0. shizzl / mashizzl
0. doubleYou
0. smickl
0. itsamee

**Comment by wesleymostien** [comment]
1. everee / evry
0. listr
0. peeq / sneeq-a-peeq
0. bizzybee / bizzeebee / bizzyme / bizzzee
0. beeq / beeqeepr
0. beezneez / beesness
0. beeyond
0. honneybee / honee / honnee / honeebee / honny 
0. beecauze / beecauz / beecoz
0. eezee
0. stuffr / stuffluv
0. shizzl / mashizzl
0. doubleYou
0. smickl
0. itsamee
